package com.jumeng.shop.db.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CACHE_MODEL".
 */
public class CacheModel {

    private Long id;
    private String name;
    private String json;
    private Long time;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CacheModel() {
    }

    public CacheModel(Long id) {
        this.id = id;
    }

    public CacheModel(Long id, String name, String json, Long time) {
        this.id = id;
        this.name = name;
        this.json = json;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getJson() {
        return json;
    }

    public void setJson(String json) {
        this.json = json;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
