package com.jumeng.shop.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.jumeng.shop.db.model.TestModel;

import com.jumeng.shop.db.dao.TestModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testModelDaoConfig;

    private final TestModelDao testModelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testModelDaoConfig = daoConfigMap.get(TestModelDao.class).clone();
        testModelDaoConfig.initIdentityScope(type);

        testModelDao = new TestModelDao(testModelDaoConfig, this);

        registerDao(TestModel.class, testModelDao);
    }
    
    public void clear() {
        testModelDaoConfig.getIdentityScope().clear();
    }

    public TestModelDao getTestModelDao() {
        return testModelDao;
    }

}
