package com.jumeng.shop.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.jumeng.shop.db.model.CacheModel;

import com.jumeng.shop.db.dao.CacheModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheModelDaoConfig;

    private final CacheModelDao cacheModelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheModelDaoConfig = daoConfigMap.get(CacheModelDao.class).clone();
        cacheModelDaoConfig.initIdentityScope(type);

        cacheModelDao = new CacheModelDao(cacheModelDaoConfig, this);

        registerDao(CacheModel.class, cacheModelDao);
    }
    
    public void clear() {
        cacheModelDaoConfig.getIdentityScope().clear();
    }

    public CacheModelDao getCacheModelDao() {
        return cacheModelDao;
    }

}
